name: Build Windows Installer

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: PyInstaller Windows
      uses: porridge/pyinstaller-action-windows@main
      with:
        path: .
    - uses: actions/upload-artifact@v2
      with:
        name: windows-executable
        path: dist/windows

