name: Release workflow

on:
  push:
    tags:
    - 'v*'

jobs:
  build_and_upload:
    name: Build and upload Windows binary
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: PyInstaller Windows
      uses: porridge/pyinstaller-action-windows@main
      with:
        path: .
        spec: "--windowed tabliczka.spec"
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: true
        prerelease: true
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./dist/windows/tabliczka.exe
        asset_name: tabliczka-${{ github.ref }}.exe
        asset_content_type: application/vnd.microsoft.portable-executable
